[package]
name = "storage-interface"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos storage interface"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
crossbeam-channel = "0.5.4"
once_cell = "1.10.0"
parking_lot = "0.12.0"
rayon = "1.5.2"
serde = { version = "1.0.137", default-features = false }
thiserror = "1.0.31"

aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-secure-net = { path = "../../secure/net" }
aptos-state-view = { path = "../state-view" }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }

scratchpad = { path = "../scratchpad" }

move-core-types = { git = "https://github.com/move-language/move", rev = "93c96eb0d1ed6ee6577ff73f07d44ef6e7869fbd", features = ["address32"] }

[dev-dependencies]
assert_unordered = "0.1.1"

aptos-types = { path = "../../types", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["aptos-types/fuzzing"]
