[package]
name = "aptosdb-indexer"
version = "0.1.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "AptosDB Internal Indexer"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
byteorder = "1.4.3"
num-derive = "0.3.3"
proptest = { version = "1.0.0", optional = true }
proptest-derive = { version = "0.3.0", optional = true }
serde = "1.0.137"

aptos-config = { path = "../../config" }
aptos-crypto = { path = "../../crates/aptos-crypto" }
aptos-infallible = { path = "../../crates/aptos-infallible" }
aptos-logger = { path = "../../crates/aptos-logger" }
aptos-metrics-core = { path = "../../crates/aptos-metrics-core" }
aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers", optional = true }
aptos-rocksdb-options = { path = "../rocksdb-options" }
aptos-state-view = { path = "../state-view" }
aptos-temppath = { path = "../../crates/aptos-temppath", optional = true }
aptos-types = { path = "../../types" }
aptos-vm = { path = "../../aptos-move/aptos-vm" }
schemadb = { path = "../schemadb" }
scratchpad = { path = "../scratchpad" }
storage-interface = { path = "../storage-interface" }

move-core-types = { git = "https://github.com/move-language/move", rev = "93c96eb0d1ed6ee6577ff73f07d44ef6e7869fbd", features = ["address32"] }
move-resource-viewer = { git = "https://github.com/move-language/move", rev = "93c96eb0d1ed6ee6577ff73f07d44ef6e7869fbd" }

[dev-dependencies]
proptest = "1.0.0"
proptest-derive = "0.3.0"
rand = "0.7.3"

aptos-proptest-helpers = { path = "../../crates/aptos-proptest-helpers" }
aptos-types = { path = "../../types", features = ["fuzzing"] }
schemadb = { path = "../schemadb", features = ["fuzzing"] }

[features]
default = []
fuzzing = ["proptest", "proptest-derive", "aptos-proptest-helpers", "aptos-temppath", "aptos-crypto/fuzzing", "aptos-types/fuzzing", "schemadb/fuzzing", "scratchpad/fuzzing"]
