[alias]
xclippy = [
  "clippy",
  "--workspace",
  "--all-targets",
  "--",
  "-Dwarnings",
  "-Wclippy::all",
  "-Aclippy::unit_arg",
  "-Aclippy::mixed_read_write_in_expression",
  "-Aclippy::new-without-default",
  "-Aclippy::rc_buffer",
  "-Aclippy::upper_case_acronyms",
  "-Aclippy::len-without-is-empty",
  "-Aclippy::from-iter-instead-of-collect",
  "-Aclippy::while-let-on-iterator",
  "-Aclippy::bool-assert-comparison",
  "-Aclippy::needless-collect",
  "-Aclippy::enum-variant-names",
  "-Aclippy::self-named-constructors",
]

[build]
rustflags = ["--cfg", "tokio_unstable"]

[net]
git-fetch-with-cli = true
