[package]
name = "aptos-rest-client"
version = "0.0.0"
authors = ["Aptos Labs <opensource@aptoslabs.com>"]
description = "Aptos REST client"
repository = "https://github.com/aptos-labs/aptos-core"
homepage = "https://aptoslabs.com"
license = "Apache-2.0"
publish = false
edition = "2021"

[features]
default = ["dpn"]
dpn = []

[dependencies]
anyhow = "1.0.57"
bcs = { git = "https://github.com/aptos-labs/bcs", rev = "2cde3e8446c460cb17b0c1d6bac7e27e964ac169" }
bytes = "1.2.1"
futures = "0.3.17"
hex = "0.4.3"
poem-openapi = { version = "2.0.10", features = ["url"] }
reqwest = { version = "0.11.10", features = ["json", "cookies", "blocking"] }
serde = { version = "1.0.137", features = ["derive"] }
serde_json = "1.0.81"
thiserror = "1.0.32"
tokio = { version = "1.21.0", features = ["full"] }
url = "2.2.2"

aptos-api-types = { path = "../../api/types" }
aptos-crypto = { path = "../aptos-crypto" }
aptos-infallible = { path = "../aptos-infallible" }
aptos-logger = { path = "../aptos-logger" }
aptos-types = { path = "../../types" }

move-binary-format = { git = "https://github.com/move-language/move", rev = "93c96eb0d1ed6ee6577ff73f07d44ef6e7869fbd" }
move-core-types = { git = "https://github.com/move-language/move", rev = "93c96eb0d1ed6ee6577ff73f07d44ef6e7869fbd", features = ["address32"] }
